name: vhmodels-nicheformer
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - numpy==1.26.4
    - pandas==1.5.3
    - scipy==1.11.4
    - numba==0.60.0
    - anndata==0.10.9
    - torch==2.9.1+cu126
    - transformers==4.49.0
    - huggingface_hub==0.29.3
